"""
ComfyUI Aria2c HuggingFace Downloader
Fast, resumable downloads from HuggingFace using aria2c
"""

from .aria2c_hf_downloader import NODE_CLASS_MAPPINGS as ARIA2C_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ARIA2C_DISPLAY_MAPPINGS
from .hf_downloader_fallback import NODE_CLASS_MAPPINGS as FALLBACK_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as FALLBACK_DISPLAY_MAPPINGS

# Combine both node types
NODE_CLASS_MAPPINGS = {**ARIA2C_MAPPINGS, **FALLBACK_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**ARIA2C_DISPLAY_MAPPINGS, **FALLBACK_DISPLAY_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
